// Generated by CoffeeScript 1.7.1
'use strict';
var quoteServices;

quoteServices = angular.module('quoteServices', []);

quoteServices.factory('quoteService', function() {
  var addQuotes, order, quotes, shuffleQuotes, shuffledQuotes, videoPlaying;
  quotes = [];
  shuffledQuotes = [];
  order = 0;
  videoPlaying = false;
  addQuotes = function(quotes) {
    return quotes = quotes;
  };
  shuffleQuotes = function(quotes) {
    var i, j, _i, _ref, _ref1;
    for (i = _i = _ref = quotes.length - 1; _ref <= 1 ? _i <= 1 : _i >= 1; i = _ref <= 1 ? ++_i : --_i) {
      j = Math.floor(Math.random() * (i + 1));
      _ref1 = [quotes[j], quotes[i]], quotes[i] = _ref1[0], quotes[j] = _ref1[1];
    }
    shuffledQuotes = quotes;
    return shuffledQuotes;
  };
  return {
    getOrder: function() {
      return order;
    },
    shuffleQuotes: function(quotes) {
      return shuffleQuotes(quotes);
    },
    addQuotes: function(quotes) {
      return addQuotes(quotes);
    },
    infoScreen: function() {
      return infoScreen();
    }
  };
});
